# V0.1
name: Ctypes Generation

on: [push, workflow_dispatch]
  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - run:
            py .\ctypes_generation\generate.py